#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "pid.c"

int state = 0;

task sensorRead() {
	while(true) {
		//default state
		state = 0;
		//TODO test for line
	}
}

task main() {
	while (true) {
		switch (state) {
		case 0:

		case 1:

		}
	}
}
