#pragma config(Sensor, S1,     line,           sensorEV3_Color)
#pragma config(Sensor, S2,     gyro,           sensorEV3_Gyro)
#pragma config(Motor,  motorB,          left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int state = 0;

task sensorRead() {
	while(true) {
		//default state
		state = 0;
		if(getColorReflected(line)<20){
			state=1;
	}
}

task main() {
	while (true) {
		switch (state) {
		case 0:

		case 1:

		}
	}
}
